export const DUMMY_PROVIDERS = [
  {
    itemId: '1086',
    itemLabel: 'Top თამაშები',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAAA2AAAAJGNkOTY3ODY4LTQ1ZmQtNGM2Ny1hMjdjLTNmZThjZTlkNzg2NA',
    itemRouteName: 'top-games',
  },
  {
    itemId: '2122',
    itemLabel: 'EGT Interactive',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAABFAAAAJDBlYjExMTUxLWNmOTEtNDhjOC05OWRiLTUwYTI0YjU2OGVlZg',
    itemRouteName: 'egt',
  },
  {
    itemId: '2269',
    itemLabel: 'Steady Games',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAAA0AAAAJGNmZTg2NjkyLThhZjMtNDQxNy04YjVkLTBkMDM5MDRhMzQ0NQ',
    itemRouteName: 'steady-games',
  },
  {
    itemId: '2298',
    itemLabel: 'Pragmatic Play',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAAAxAAAAJDkzYmZlYTM2LTBiZGYtNDY2NC04NjBhLWY0ZGQ3NDg1YjA4OA',
    itemRouteName: 'pragmatic-play',
  },
  {
    itemId: '2272',
    itemLabel: 'Elk Gaming',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAAA0AAAAJDFiNDhkMzk3LTVjOTYtNGFiYy1iZGNjLTFhOGIzMGFmOTY2Yg',
    itemRouteName: 'elk-gaming',
  },
  {
    itemId: '2307',
    itemLabel: 'EGT Digital',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAABGAAAAJGIxMGM5ZjhkLTNlYjUtNGJmYi1hZDhiLThkNWYxMzM0MWY5Nw',
    itemRouteName: 'egt-digital',
  },
  {
    itemId: '2306',
    itemLabel: 'BTG',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAABIAAAAJDhkYWQzZmM1LTRkMDUtNDEzMS1hN2M5LWU2Yjc0ODQ0YWQ5Yw',
    itemRouteName: 'bigtimegaming',
  },
  {
    itemId: '2302',
    itemLabel: 'Relax Gaming',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAABHAAAAJDA2MmU4YWJjLTYzNmMtNDRiZi04MThjLTA0MWFlMjUyN2JkOA',
    itemRouteName: 'relax-gaming',
  },
  {
    itemId: '2299',
    itemLabel: 'Hacksaw',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAABAAAAAJDQ4MDMwNDE2LTc5ZmEtNDlhZi04MmY3LWIwZTMyNTczMGZkOQ',
    itemRouteName: 'hacksaw',
  },
  {
    itemId: '2166',
    itemLabel: 'Endorphina',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAAA1AAAAJDdhOTIyNGE0LWI2MTUtNGU0NC04ZTc3LTE5YWM4ZTA4ZTljOA',
    itemRouteName: 'endorphina',
  },
  {
    itemId: '2289',
    itemLabel: 'Playson',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAAA-AAAAJDg5ZThiMjg0LTkwODMtNGY5Yi04Zjk2LTFjNjhkMDhlYzY1ZQ',
    itemRouteName: 'playson',
  },
  {
    itemId: '2303',
    itemLabel: 'Spinomenal',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAABBAAAAJGEwOTU3N2E2LWM3YjEtNGI0Ny05YzRmLTA5MmNkYzBlMDA2ZA',
    itemRouteName: 'spinomenal',
  },
  {
    itemId: '2291',
    itemLabel: 'Novomatic',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAAAyAAAAJDJlN2I5YmRhLTU3NGUtNDcwYS05ZTZiLTM5NzQ0YWUzYjI1Yw',
    itemRouteName: 'novomatic',
  },
  {
    itemId: '2280',
    itemLabel: 'Igrosoft',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAAA3AAAAJDgwYjEwM2FjLWExNDQtNDAwOC1iYjg0LTczODVmMzcyZTM3Mw',
    itemRouteName: 'igrosoft',
  },
  {
    itemId: '2287',
    itemLabel: 'Thunderkick',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAAAyAAAAJDk5MDlhMzhlLTUzOTAtNDBkYi05M2NiLTBkNzllNGFkMTI3YQ',
    itemRouteName: 'thunderkick',
  },
  {
    itemId: '2282',
    itemLabel: 'Push Gaming',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAAAwAAAAJDEzYmU3MGZlLWU5NTgtNDBiYy04MTYzLTMwZjZlMzgyYjA2MQ',
    itemRouteName: 'push-gaming',
  },
  {
    itemId: '2304',
    itemLabel: '3 Oaks Gaming',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAABAAAAAJDQ3MTViOTMwLTcxYTAtNGFmOS05YTI3LWVlY2QyYTNkYThkYg',
    itemRouteName: '3-oaks-gaming',
  },
  {
    itemId: '2234',
    itemLabel: 'PG Soft',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAAA0AAAAJDMyZjM3NTFhLWY3MTAtNGU4Zi1hYTM3LTkwNzQ0YmY1NTczZA',
    itemRouteName: 'pg-soft',
  },
  {
    itemId: '2278',
    itemLabel: 'Spearhead',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAAAzAAAAJGVmNWE0ZWJlLWQ1M2MtNGVkNy1hYjY2LWU4YTNjZjU4Y2I3NA',
    itemRouteName: 'spearhead',
  },
  {
    itemId: '2216',
    itemLabel: 'Quickspin',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAAA1AAAAJDU2NDdjZDMwLWY3ODAtNGMxMi1iODJiLTM3MmIwMGFjYTMxOA',
    itemRouteName: 'quickspin',
  },
  {
    itemId: '2241',
    itemLabel: 'Wazdan',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAAA1AAAAJDJhMmUwM2Q1LTk1NmItNGQ2ZS04ZDBiLTcxZWEyZjI0ZTdhZQ',
    itemRouteName: 'wazdan',
  },
  {
    itemId: '2161',
    itemLabel: 'Booming',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAAA0AAAAJDkyNDE1ZTdjLWY5MmQtNDBlYS04MzAxLWVkNDFmZWY1NjA1Zg',
    itemRouteName: 'booming',
  },
  {
    itemId: '2195',
    itemLabel: 'Microgaming',
    icon: 'https://cdn.betlive.com/AAEAAQAAAAAAAAA0AAAAJDFlYTFmZjFkLWQwMzUtNDM0OS05ZWUzLTVjNWYwODg0ZTIwMA',
    itemRouteName: 'microgaming',
  },
];
